version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "grafana/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
