services:
  db:
    image: "postgres:16"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: grafana
    ports:
      - "6543:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

  grafana:
    image: "grafana/grafana:latest"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: user
      GF_DATABASE_PASSWORD: pass
      GF_DATABASE_SSL_MODE: disable
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana


volumes:
  postgres:
  grafana:
