services:
  db:
    image: "postgres:16"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: grafana
    ports:
      - "6543:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

  grafana:
    image: "grafana/grafana:latest"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: db:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: user
      GF_DATABASE_PASSWORD: pass
      GF_DATABASE_SSL_MODE: disable
    depends_on:
      - db
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin
      DOCKER_INFLUXDB_INIT_ORG: bennett
      DOCKER_INFLUXDB_INIT_BUCKET: data
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - timescaledb:/home/postgres/pgdata/data

volumes:
  postgres:
  grafana:
  influxdb:
  timescaledb:
