services:
  grafana:
    # use Dockerfile so that version matches production
    # uses sqlite for a very simple smoke test 
    build:
        dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana:
