name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  "5 6 * * MON"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: "opensafely-core/setup-action@v1"
      with:
        python-version: "3.12"
        install-just: true

    - uses: actions/create-github-app-token@v1
      id: generate-token
      with:
        app-id: ${{ secrets.CREATE_PR_APP_ID }}
        private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}

    - uses: bennettoxford/update-dependencies-action@v1
      with:
        token: ${{ steps.generate-token.outputs.token }}
        automerge: false
